### PR TITLE
Bugfix: Date picker not resetting date and time on subsequent open

### PR DESCRIPTION
**Pull request by aleckan53**
This PR implements a solution for this bug https://github.com/marleymarl/geotime/issues/11

Also added a few extras:
- refactored `<Modal/>` to a reusable `<DatePickerModal/>` component
- removed unused `marker` prop from the `Modal`
- formating time to utc on save
- storing `moment` obj in the state (to make the pickers controllable)

Not sure if the new time formatting is ok. Please someone confirm:
Used to be = `00:03:00 GMT-0700 (Pacific Daylight Time)` ---> `02:00:00 AM`

p.s sorry for a single commit. had to stash and move all changes to a newly cloned repo due to some ssh issues

### CODE REVIEW

**Comment by heldersepu** [comment]
Love this refactor! did not see it when I did my fix for #11 
will resolve conflicts and merge shortly...

**Comment by aleckan53** [comment]
> Love this refactor! did not see it when I did my fix for #11
> will resolve conflicts and merge shortly...

Thanks for taking care of that!

**Comment by heldersepu** [comment]
> @heldersepu Thanks for taking care of that!

Thank you, for the quick reply...
`import DateTimePickerModal from './components/DateTimePicketModal'`
was that t a typo? 
> Picke**t**Modal
I'm fixing it...

**Comment by aleckan53** [comment]
> > @heldersepu Thanks for taking care of that!
> 
> Thank you, for the quick reply...
> `import DateTimePickerModal from './components/DateTimePicketModal'`
> was that t a typo?
> 
> > Picke**t**Modal
> 
> I'm fixing it...

oh yeah, good call. Sorry about that

**Pull request merged**
